run-name: Create Theme Preview by @${{ github.actor }}
on:
  issue_comment:      
    types: [created]    
jobs:                   
  deploy:
    name: Preview
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '!preview')
    steps:
      - uses: F3C-Shopify/shopify-theme-preview@v1
        with:
          shopify_flag_store: 'theme-preview-example.myshopify.com'
          shopify_cli_theme_token: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
